platform: linux
image_resource:
  type: docker-image
  source: {repository: quay.io/desource/fedora, tag: build}

run:
  path: container/build.sh
  
inputs:
  - name: glibc
  - name: container

outputs:
  - name: out
